apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: kedge.faros.sh
spec:
  permissionClaims:
  - group: ""
    resource: secrets
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - group: ""
    resource: namespaces
    verbs: ["get", "list", "watch", "create"]
  - group: ""
    resource: configmaps
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - group: ""
    resource: serviceaccounts
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - group: "rbac.authorization.k8s.io"
    resource: clusterroles
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - group: "rbac.authorization.k8s.io"
    resource: clusterrolebindings
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  resources:
  - group: kedge.faros.sh
    name: placements
    schema: v260215-f3ac411.placements.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: sites
    schema: v260215-f3ac411.sites.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: users
    schema: v260215-f3ac411.users.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: virtualworkloads
    schema: v260215-f3ac411.virtualworkloads.kedge.faros.sh
    storage:
      crd: {}
status: {}
