apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: tenancy.kedge.faros.sh
spec:
  resources:
  - group: tenancy.kedge.faros.sh
    name: users
    schema: v260217-6fee47f.users.tenancy.kedge.faros.sh
    storage:
      crd: {}
status: {}
