{{- if and (not .Values.agent.hub.existingSecret) .Values.agent.hub.kubeconfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kedge-agent.fullname" . }}-hub-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kedge-agent.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.agent.hub.kubeconfig | b64enc }}
{{- end }}
