apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: kedge.faros.sh
spec:
  permissionClaims:
  - resource: secrets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - resource: namespaces
    verbs:
    - get
    - list
    - watch
    - create
  - resource: configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - resource: serviceaccounts
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - group: rbac.authorization.k8s.io
    resource: clusterroles
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - group: rbac.authorization.k8s.io
    resource: clusterrolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - group: tenancy.kcp.io
    identityHash: __TENANCY_IDENTITY_HASH__
    resource: workspaces
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  resources:
  - group: kedge.faros.sh
    name: edges
    schema: v260225-fa2316e.edges.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: placements
    schema: v260217-7570c9b.placements.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: servers
    schema: v260223-f2c2894.servers.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: sites
    schema: v260217-7570c9b.sites.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: users
    schema: v260217-7570c9b.users.kedge.faros.sh
    storage:
      crd: {}
  - group: kedge.faros.sh
    name: virtualworkloads
    schema: v260219-7bf8d83.virtualworkloads.kedge.faros.sh
    storage:
      crd: {}
status: {}
