image:
  hub:
    repository: ghcr.io/faroshq/kedge-hub
    tag: "7558a55-dirty"  # defaults to .Chart.AppVersion
    pullPolicy: IfNotPresent
  kcp:
    repository: ghcr.io/kcp-dev/kcp
    tag: "v0.30.0"
    pullPolicy: IfNotPresent

hub:
  hubExternalURL: "https://hub.faros.sh"
  devMode: false
  # -- TLS configuration for hub serving
  staticAuthToken: "qxdo7t3qXY1hak233FJhTZtsMA2kFXfzXQhYw8ZU8e8="
  tls:
    certManager:
      enabled: true 
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
        - "hub.faros.sh"
    selfSigned:
      enabled: false
  
    
#idp:
#  issuerURL: "https://idp.faros.sh"
#  clientID: "kedge"
#  clientSecret: "Z2Fyc2lha2FsYmlzdmFuZGVuekWplCg=="

ingress:
  enabled: true
  className: "cloudflare-tunnel"
  annotations:
    cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: "https"
    cloudflare-tunnel-ingress-controller.strrl.dev/proxy-ssl-verify: "off"
  hosts:
    - host: hub.faros.sh
      paths:
        - path: /
          pathType: ImplementationSpecific