services:
  jekyll:
    image: jekyll/jekyll:4
    container_name: kedge-docs
    environment:
      - JEKYLL_ENV=development
      - PAGES_REPO_NWO=faroshq/faros-kedge
    command: >
      sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --baseurl '' --force_polling --livereload"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    working_dir: /srv/jekyll

volumes:
  bundle_cache:
