{{- if and .Values.kcp.external.enabled (not .Values.kcp.external.existingSecret) .Values.kcp.external.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kedge-hub.kcpKubeconfigSecretName" . }}
  labels:
    {{- include "kedge-hub.labels" . | nindent 4 }}
type: Opaque
data:
  admin.kubeconfig: {{ .Values.kcp.external.kubeconfig | b64enc }}
{{- end }}
