{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kedge-hub.fullname" . }}-dex
  labels:
    {{- include "kedge-hub.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  client-secret: {{ include "kedge-hub.dexClientSecret" . }}
{{- end }}
