{{- if and .Values.tls.selfSigned.enabled (not .Values.tls.existingSecret) }}
{{- $fullname := include "kedge-hub.fullname" . }}
{{- $dnsNames := concat
  (list "localhost" $fullname (printf "%s-dex" $fullname)
    (printf "%s.%s.svc" $fullname .Release.Namespace)
    (printf "%s-dex.%s.svc" $fullname .Release.Namespace))
  .Values.tls.selfSigned.dnsNames
}}
{{- $ips := list }}
{{- range .Values.tls.selfSigned.ipAddresses }}
{{- $ips = append $ips . }}
{{- end }}
{{- $cert := genSelfSignedCert "kedge-hub" $ips $dnsNames 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kedge-hub.tlsSecretName" . }}
  labels:
    {{- include "kedge-hub.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
