apiVersion: v1
kind: Service
metadata:
  name: {{ include "kedge-hub.fullname" . }}
  labels:
    {{- include "kedge-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.hub.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "kedge-hub.selectorLabels" . | nindent 4 }}
